<a href="https://colab.research.google.com/github/camilacruz-cs/PretaLab/blob/main/mod3/%20aula2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Montando o drive

In [ ]:
# Montando o Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd /content/drive/MyDrive/Colab Notebooks/PretaLab - Python para análise de dados/

/content/drive/MyDrive/Colab Notebooks/PretaLab - Python para análise de dados

In [ ]:
import os
print(os.getcwd())

/content/drive/MyDrive/Colab Notebooks/PretaLab - Python para análise de dados

In [ ]:
!ls

'Módulo 1'  'Módulo 2'	'Módulo 3'  'Módulo 4'	'Módulo 5'   Projetos

##Métodos avançados com Biblioteca Python para análise de dados

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

PNAD CONTINUA DE 2024 - 2 TRIMESTRE (ABRIL-MAIO-JUNHO)

* Coluna idade = Varia entre 19 e 65 anos.

In [ ]:
#Leitura dos dados

pnad = pd.read_csv('/content/pnad - pnad.csv')
pnad

,ano,sigla_uf,sigla_uf_nome,id_pessoa,V2007,V2009,V2010,V4001,V4003,V4009,...,V4033,V403412,V4039,V4039C,V4040,V4043,V40431,V4048,V405012,V4056
0,2024,AP,Amapá,160000321011101,Mulher,27,4,1,NaN,1.0,...,1.0,1200.0,36.0,36.0,2.0,NaN,NaN,NaN,NaN,NaN
1,2024,AP,Amapá,160000321021101,Mulher,33,4,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,AP,Amapá,160000321021102,Homem,27,4,1,NaN,1.0,...,1.0,800.0,30.0,30.0,4.0,NaN,NaN,NaN,NaN,NaN
3,2024,AP,Amapá,160000321031104,Mulher,27,1,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,AP,Amapá,160000321031102,Mulher,78,4,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365663,2024,BA,Bahia,290026766051101,Mulher,45,5,2,2.0,1.0,...,NaN,NaN,40.0,40.0,4.0,NaN,NaN,NaN,NaN,NaN
365664,2024,BA,Bahia,290250365101101,Homem,22,2,2,2.0,1.0,...,NaN,NaN,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN
365665,2024,BA,Bahia,290211270071102,Mulher,29,4,2,2.0,1.0,...,NaN,NaN,30.0,12.0,4.0,NaN,NaN,NaN,NaN,NaN
365666,2024,BA,Bahia,290083340131101,Mulher,19,2,2,2.0,1.0,...,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
365667,2024,BA,Bahia,290263738021102,Mulher,60,4,2,2.0,1.0,...,NaN,NaN,20.0,20.0,4.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
pnad.head(4)

,ano,sigla_uf,sigla_uf_nome,id_pessoa,V2007,V2009,V2010,V4001,V4003,V4009,...,V4033,V403412,V4039,V4039C,V4040,V4043,V40431,V4048,V405012,V4056
0,2024,AP,Amapá,160000321011101,Mulher,27,4,1,NaN,1.0,...,1.0,1200.0,36.0,36.0,2.0,NaN,NaN,NaN,NaN,NaN
1,2024,AP,Amapá,160000321021101,Mulher,33,4,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,AP,Amapá,160000321021102,Homem,27,4,1,NaN,1.0,...,1.0,800.0,30.0,30.0,4.0,NaN,NaN,NaN,NaN,NaN
3,2024,AP,Amapá,160000321031104,Mulher,27,1,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pnad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365668 entries, 0 to 365667
Data columns (total 26 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ano            365668 non-null  int64
 1   sigla_uf       365668 non-null  object
 2   sigla_uf_nome  365668 non-null  object
 3   id_pessoa      365668 non-null  int64
 4   V2007          365668 non-null  object
 5   V2009          365668 non-null  int64
 6   V2010          365668 non-null  int64
 7   V4001          365668 non-null  int64
 8   V4003          172177 non-null  float64
 9   V4009          207824 non-null  float64
 10  V4010          207824 non-null  float64
 11  V40121         4144 non-null    float64
 12  V4014          28733 non-null   float64
 13  V40151         5191 non-null    float64
 14  V4028          19283 non-null   float64
 15  V4029          120211 non-null  float64
 16  V4033          203680 non-null  float64
 17  V403412        203084 non-null  float64
 18  V4039          207824 non-null  float64
 19  V4039C         207824 non-null  float64
 20  V4040          207824 non-null  float64
 21  V4043          6913 non-null    float64
 22  V40431         198 non-null     float64
 23  V4048          2400 non-null    float64
 24  V405012        6693 non-null    float64
 25  V4056          6913 non-null    float64
dtypes: float64(18), int64(5), object(3)
memory usage: 72.5+ MB

###Tratamento e limpeza de dados - ETL

In [ ]:
# 2. Renomear as colunas com base no dicionário fornecido
colunas_dicionario = {
    'V2007': 'sexo',
    'V4009': 'idade',
    'V4001': 'condicao_de_trabalho',
    'V4003': 'renda',
    'sigla_uf': 'estado',
    'V2010': 'raca_cor',
    'V4039': 'horas_trabalhadas'
}

In [ ]:
df = pnad.rename(columns=colunas_dicionario)
df

,ano,estado,sigla_uf_nome,id_pessoa,sexo,raca_cor,V2010,condicao_de_trabalho,renda,idade,...,V4033,V403412,horas_trabalhadas,V4039C,V4040,V4043,V40431,V4048,V405012,V4056
0,2024,AP,Amapá,160000321011101,Mulher,27,4,1,NaN,1.0,...,1.0,1200.0,36.0,36.0,2.0,NaN,NaN,NaN,NaN,NaN
1,2024,AP,Amapá,160000321021101,Mulher,33,4,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,AP,Amapá,160000321021102,Homem,27,4,1,NaN,1.0,...,1.0,800.0,30.0,30.0,4.0,NaN,NaN,NaN,NaN,NaN
3,2024,AP,Amapá,160000321031104,Mulher,27,1,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,AP,Amapá,160000321031102,Mulher,78,4,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365663,2024,BA,Bahia,290026766051101,Mulher,45,5,2,2.0,1.0,...,NaN,NaN,40.0,40.0,4.0,NaN,NaN,NaN,NaN,NaN
365664,2024,BA,Bahia,290250365101101,Homem,22,2,2,2.0,1.0,...,NaN,NaN,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN
365665,2024,BA,Bahia,290211270071102,Mulher,29,4,2,2.0,1.0,...,NaN,NaN,30.0,12.0,4.0,NaN,NaN,NaN,NaN,NaN
365666,2024,BA,Bahia,290083340131101,Mulher,19,2,2,2.0,1.0,...,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
365667,2024,BA,Bahia,290263738021102,Mulher,60,4,2,2.0,1.0,...,NaN,NaN,20.0,20.0,4.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['ano', 'estado', 'sigla_uf_nome', 'id_pessoa', 'sexo', 'raca_cor',
       'V2010', 'condicao_de_trabalho', 'renda', 'idade', 'V4010', 'V40121',
       'V4014', 'V40151', 'V4028', 'V4029', 'V4033', 'V403412',
       'horas_trabalhadas', 'V4039C', 'V4040', 'V4043', 'V40431', 'V4048',
       'V405012', 'V4056'],
      dtype='object')

In [ ]:
pnad_renomeada = pnad_renomeada.DataFrame(pnad_renomeada, columns=['ano', 'estado','sigla_uf_nome','id_pessoa','sexo','idade', 'raca_cor','condicao_de_trabalho','trabalho_informal','renda'])

AttributeError: 'DataFrame' object has no attribute 'DataFrame'